# Generated by Django 5.0.4 on 2024-04-15 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onememos', '0003_memo_tb_writer_mail_memo_tb_writer_nm'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='memo_tb',
            name='writer_mail',
        ),
        migrations.RemoveField(
            model_name='memo_tb',
            name='writer_nm',
        ),
    ]
