# Generated by Django 5.0.4 on 2024-04-15 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onememos', '0005_memo_tb_writer_mail_memo_tb_writer_nm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memo_tb',
            name='writer_mail',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='memo_tb',
            name='writer_nm',
            field=models.CharField(max_length=20),
        ),
    ]
